services:
  postgres:
    image: postgres:15
    container_name: storage_db
    restart: always
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - storage-net
  storage-service:
    image: psup-storage/storage-service
    container_name: storage_service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/storage_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/storage_db
      - PRODUCT_SERVICE_BASE_URL=http://product-service:8080
      - KAFKA_BROKERS=broker-1:19092,broker-2:19092,broker-3:19092
      - KAFKA_DELIVERY_TIMEOUT_MS=20000
      - KAFKA_LINGER_MS=0
      - KAFKA_REQUEST_TIMEOUT_MS=10000
      - KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION=5
    volumes:
      - ~/Universal_Trade_Platform/logs/storage-service:/root/Universal_Trade_Platform/logs/storage-service
    networks:
      - storage-net
      - psup-shared-net

networks:
  storage-net:
    driver: bridge
  psup-shared-net:
    external: true