services:
  postgres:
    image: postgres:15
    container_name: storage_db
    restart: always
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"