server:
  port: 8082
spring:
  application:
    name: STORAGE_SERVICE
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/storage_db
    username: admin
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:/db/main-changelog.xml
    default-schema: public
    url: jdbc:postgresql://localhost:5434/storage_db
    user: admin
    password: admin
logging:
  level:
    org.springframework.data.r2dbc: DEBUG

